In [6]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np

## np.array(list)相当于类型转换函数，将list转换为array
## array.shape 表示array的形状
## array.ndim 表示array的维数,相当于len(array.shape)
## array.size 表示array中总共有多少元素
## array.nbytes 表示array所占用的内存
a_array = np.array([1, 2, 3])## 一维形式（一行三列）

b_array = np.array([[1, 2, 4], [4, 5, 6]]) ## 二维形式（两行三列），更高维形式可以通过多维list生成 嵌套列表中的元素个数必须相同，否则只会读取第一个列表中的元素


In [ ]:
## 创建只含一种元素的array的方法: np.zeros(shapes); np.ones(shapes); np.full(shapes, number)
## shape是一个包含想生成array的形状参数的元组（几行几列等等）,number表示要填充的数字
## np.zeros表示array中的元素全为0, np.ones表示array中的元素全为1
## 默认生成的array中的元素类型为float,可以在函数中加上可选参数dtype=int进行类型转换
c_array = np.zeros((1, 2), dtype = int)  ## (1, 2)表示一行二列
c_array

d_array = np.zeros((3,), dtype = int)
d_array

e_array = np.full((2, 3), 5, dtype = int)
e_array

In [ ]:
## np.arange(start, stop, step)
## np.linspace(start, stop, num, endpoint = True) ——将[start, stop] num-1等分， endpoint为True时表示区间包含stop,为False时表示区间不包含stop
## 两者同样可以传递dtype参数改变元素类型

np.linspace(1, 3, 5, dtype = float)
np.linspace(1, 3, 5, endpoint = False)

In [ ]:
## np.random.rand(d1, d2, ...) 从0到1中随机挑取元素生成array; d1, d2, ...表示该维数含有元素的个数
## np.random.randint(start [,stop], size) 从start到stop-1中随机挑取整数元素生成array, size表示array中所含元素的个数

np.random.rand(2, 10)
np.random.randint(1, 101, 12)

In [ ]:
## array和list一样有slice,方法也基本一样
## 不同的是高维的slice: array[start1: end1, start2: end2, ...]; list[start1: end1][start2: end2]...
## 如果改变slice的array/list,原array/list中的对应元素也会改变

In [ ]:
## 复制一个array: array.copy()

In [50]:
## 数值运算：可以用数值操作符来改变array中的元素
a_array
a = a_array + 1 # array中所有元素数值+1; list做不到这一点
a
c = a_array + a # array1与array2对应元素相加
c

array([1, 2, 3])

array([2, 3, 4])

array([3, 5, 7])

In [ ]:
## 如果要做矩阵乘法的话可以用np.dot(A, B)
## 如果A, B都是1维的，结果是两个向量的内积
## 如果A, B有一个是高维的，那么结果是矩阵乘积：AB (注意，必须符合矩阵乘法的前提, 而且矩阵中不能有未知数(一大遗憾)) 

In [60]:
## 比较操作符：可以用比较操作符来比较两个array中的值，返回一个全为boolean value的array
## 如果要判断两个array是否完全相同（形状以及array中的值），要用np.array_equal(array1, array2)

In [75]:
## 逻辑操作符：np.logical_and(array1, array2) 
##           np.logical_or(array1, array2)
##           np.logical_not(array)
##           array.all() 判断array中所有元素的boolean value, 只要有一个为False就返回False, 如果全为True则返回True, 可以理解为 Are all elements in the array True?
##           也可以用内建函数all(iterable)
##           array.any() 判断array中所有元素的boolean value, 只要有一个为True就返回True, 如果全为False则返回False, 可以理解为 Is there a element in the array True?
##           也可以用内建函数any(iterable)

True

In [12]:
all(np.array([1, 3, 0]))

False